import type { RawLevelDefinition } from "./parseLevel";

export const rawLevels: RawLevelDefinition[] = [
  {
    id: "twin-steps",
    name: "Ashen Threshold",
    light: [
      "##########",
      "#P.XX....#",
      "#X.....X.#",
      "#.XXX..X.#",
      "#....E...#",
      "##########",
    ],
    shadow: [
      "##########",
      "#P...XX..#",
      "#........#",
      "#....X...#",
      "#X..XE...#",
      "##########",
    ],
  },
  {
    id: "split-corridors",
    name: "Severed Cloister",
    light: [
      "##########",
      "#PXXX....#",
      "#........#",
      "#.XXXXXE.#",
      "#.X....X.#",
      "##########",
    ],
    shadow: [
      "##########",
      "#P.......#",
      "#.....XX.#",
      "#X.....E.#",
      "#X..X..XX#",
      "##########",
    ],
  },
  {
    id: "echo-turn",
    name: "Last Concord",
    light: [
      "##########",
      "#P.X....X#",
      "#X...X..X#",
      "#.XXXX...#",
      "#...XE.X.#",
      "##########",
    ],
    shadow: [
      "##########",
      "#P.X.....#",
      "#X....X..#",
      "#.......X#",
      "#....E...#",
      "##########",
    ],
  },
  {
    id: "veiled-passage",
    name: "Veiled Passage",
    light: [
      "##########",
      "#XX..X...#",
      "#P.....X.#",
      "#X.....X.#",
      "#..X...E.#",
      "##########",
    ],
    shadow: [
      "##########",
      "#..X.X...#",
      "#P.XX....#",
      "#X....X..#",
      "#XX.XX.E.#",
      "##########",
    ],
  },
  {
    id: "sanctum-knot",
    name: "Sanctum Knot",
    light: [
      "##########",
      "#....X...#",
      "#P..X....#",
      "#X..X.XE.#",
      "#.X...XXX#",
      "##########",
    ],
    shadow: [
      "##########",
      "#XXXX....#",
      "#P.....X.#",
      "#.X...XE.#",
      "#X.....X.#",
      "##########",
    ],
  },
];
